# Generated by Django 5.2.16 on 2026-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_districts',
            field=models.ManyToManyField(blank=True, related_name='agents', to='locations.district'),
        ),
    ]
