# Generated by Django 5.2.16 on 2026-08-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="service_neighborhoods",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="locations.neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.agency",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.agency",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="agency_roles", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(blank=True, to="accounts.role"),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("agency", "name"), name="unique_role_per_agency"
            ),
        ),
    ]
