# Generated by Django 5.2.16 on 2026-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deal_type_scope",
            field=models.CharField(
                choices=[
                    ("rent-residential", "اجارهٔ مسکونی"),
                    ("buy-residential", "فروش مسکونی"),
                    ("buy-commercial-property", "فروش اداری و تجاری"),
                    ("rent-commercial-property", "اجارهٔ اداری و تجاری"),
                ],
                default="rent-residential",
                max_length=40,
                verbose_name="نوع معامله",
            ),
        ),
    ]
