# Generated by Django 5.2.16 on 2026-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_deal_type_scope"),
        ("locations", "0003_seed_fardis_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="service_neighborhoods",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="locations.divarneighborhood"
            ),
        ),
    ]
