
/**
 * Create/Edit Followup Form
 */
export const FOLLOWUP_FORM = {
  title: "وظیفه / پیگیری",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات پیگیری",
      icon: "ClipboardList",
      fields: [
        {
          key: "title",
          label: "عنوان",
          type: "text",
          required: true,
          placeholder: "مثلاً پیگیری قیمت با مالک",
          validation: { required: "عنوان الزامی است" },
          span: 12,
        },
        {
          key: "type",
          label: "نوع پیگیری",
          type: "select",
          required: true,
          placeholder: "انتخاب نوع",
          options: [
            { value: "call", label: "تماس" },
            { value: "visit", label: "بازدید" },
            { value: "follow_up", label: "پیگیری" },
            { value: "other", label: "سایر" },
          ],
          defaultValue: "follow_up",
          validation: { required: "نوع پیگیری الزامی است" },
          span: 6,
        },
        {
          key: "status",
          label: "وضعیت",
          type: "select",
          required: true,
          placeholder: "انتخاب وضعیت",
          options: [
            { value: "pending", label: "در انتظار" },
            { value: "done", label: "انجام شده" },
            { value: "canceled", label: "لغو شده" },
          ],
          defaultValue: "pending",
          validation: { required: "وضعیت الزامی است" },
          span: 6,
        },
        {
          key: "user",
          label: "مسئول پیگیری",
          type: "search_select",
          required: true,
          placeholder: "جستجوی کاربر...",
          asyncSource: "/api/users/?is_active=true",
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          validation: { required: "انتخاب مسئول الزامی است" },
          span: 6,
        },
        {
          key: "due_at",
          label: "موعد انجام",
          type: "datetime",
          required: true,
          placeholder: "انتخاب تاریخ و زمان",
          validation: { required: "موعد انجام الزامی است" },
          span: 6,
        },
        {
          key: "customer",
          label: "مشتری مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی مشتری...",
          asyncSource: "/api/customers/",
          searchFields: ["full_name", "phone", "national_id"],
          displayField: "full_name",
          span: 6,
        },
        {
          key: "property",
          label: "ملک مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی ملک...",
          asyncSource: "/api/properties/",
          searchFields: ["title", "property_code"],
          displayField: "title",
          span: 6,
        },
        {
          key: "description",
          label: "توضیحات",
          type: "textarea",
          required: false,
          placeholder: "جزئیات پیگیری...",
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "completion",
      label: "تکمیل",
      icon: "CheckCircle",
      condition: (values) => values.status === "done",
      fields: [
        {
          key: "completed_at",
          label: "تاریخ تکمیل",
          type: "datetime",
          required: false,
          defaultValue: "now",
          span: 6,
        },
        {
          key: "completion_note",
          label: "نتیجه پیگیری",
          type: "textarea",
          required: false,
          placeholder: "نتیجه نهایی پیگیری...",
          rows: 4,
          span: 12,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره پیگیری", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};

/**
 * Quick Create Followup from Call Form
 * Auto-fills: customer, property from call
 */
export const QUICK_FOLLOWUP_FROM_CALL_FORM = {
  title: "ثبت پیگیری از تماس",
  description: "پیگیری جدید بر اساس نتیجه تماس ثبت می‌شود",
  tabs: null,
  fields: [
    {
      key: "title",
      label: "عنوان",
      type: "text",
      required: true,
      placeholder: "عنوان پیگیری",
      autoFill: { source: "call", field: "result", transform: (v) => `پیگیری: ${v}` },
      validation: { required: "عنوان الزامی است" },
      span: 12,
    },
    {
      key: "type",
      label: "نوع",
      type: "select",
      required: true,
      options: [
        { value: "call", label: "تماس" },
        { value: "visit", label: "بازدید" },
        { value: "follow_up", label: "پیگیری" },
        { value: "other", label: "سایر" },
      ],
      defaultValue: "follow_up",
      span: 6,
    },
    {
      key: "due_at",
      label: "موعد انجام",
      type: "datetime",
      required: true,
      defaultValue: "tomorrow",
      span: 6,
    },
    {
      key: "customer",
      label: "مشتری",
      type: "nested_display",
      required: false,
      autoFill: { source: "call", field: "customer", readOnly: true },
      displayTemplate: "{full_name} — {phone}",
      span: 6,
    },
    {
      key: "property",
      label: "ملک",
      type: "nested_display",
      required: false,
      autoFill: { source: "call", field: "related_property", readOnly: true },
      displayTemplate: "{title} — {property_code}",
      span: 6,
    },
    {
      key: "description",
      label: "توضیحات",
      type: "textarea",
      required: false,
      placeholder: "جزئیات...",
      rows: 3,
      span: 12,
    },
  ],
  actions: {
    submit: { label: "ثبت پیگیری", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};