# Generated by Django 6.0.5 on 2026-07-30 12:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('search_url', models.URLField(max_length=1000, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('discovery_interval_minutes', models.PositiveSmallIntegerField(default=15)),
                ('incremental_known_streak', models.PositiveSmallIntegerField(default=100)),
                ('incremental_max_cards', models.PositiveSmallIntegerField(default=500)),
                ('last_watermark_external_id', models.CharField(blank=True, max_length=100)),
                ('last_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('last_full_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrape_targets', to='listing.source')),
            ],
            options={
                'db_table': 'scrape_targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('full', 'Full bootstrap'), ('discovery', 'Incremental discovery'), ('refresh', 'Scheduled refresh'), ('reconciliation', 'Full token reconciliation')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('discovered_count', models.PositiveIntegerField(default=0)),
                ('queued_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('changed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('removed_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('artifact_path', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ingestion.scrapetarget')),
            ],
            options={
                'db_table': 'ingestion_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen_full_discovery_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_full_absences', models.PositiveSmallIntegerField(default=0)),
                ('last_card_fingerprint', models.CharField(blank=True, max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_memberships', to='listing.listing')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_memberships', to='ingestion.scrapetarget')),
            ],
            options={
                'db_table': 'target_listings',
            },
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='listings',
            field=models.ManyToManyField(related_name='scrape_targets', through='ingestion.TargetListing', to='listing.listing'),
        ),
        migrations.CreateModel(
            name='IngestionRunItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('discovery_order', models.PositiveIntegerField(default=0)),
                ('card_fingerprint', models.CharField(blank=True, max_length=64)),
                ('card_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('removed', 'Removed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_listing', models.BooleanField(default=False)),
                ('changed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_items', to='listing.listing')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ingestion.ingestionrun')),
            ],
            options={
                'db_table': 'ingestion_run_items',
                'ordering': ['discovery_order', 'id'],
                'indexes': [models.Index(fields=['run', 'status'], name='ingestion_r_run_id_7913e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'external_id'), name='unique_ingestion_run_external_id')],
            },
        ),
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='listing.listing')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='ingestion.ingestionrun')),
            ],
            options={
                'db_table': 'listing_snapshots',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['listing', 'observed_at'], name='listing_sna_listing_ab549b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['target', 'mode', 'created_at'], name='ingestion_r_target__83e9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['status', 'created_at'], name='ingestion_r_status_502428_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('target',), name='one_active_ingestion_run_per_target'),
        ),
        migrations.AddIndex(
            model_name='targetlisting',
            index=models.Index(fields=['target', 'last_seen_at'], name='target_list_target__8efcf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='targetlisting',
            constraint=models.UniqueConstraint(fields=('target', 'listing'), name='unique_target_listing'),
        ),
    ]
