# Generated by Django 6.0.5 on 2026-09-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
        ('locations', '0002_divarneighborhood_zone_city_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapetarget',
            name='base_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='listing_category',
            field=models.CharField(blank=True, choices=[('rent-residential', 'اجارهٔ مسکونی'), ('buy-residential', 'فروش مسکونی'), ('buy-commercial-property', 'فروش اداری و تجاری'), ('rent-commercial-property', 'اجارهٔ اداری و تجاری')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='scrapetarget',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrape_targets', to='locations.zone'),
        ),
    ]
