# Generated by Django 5.2.16 on 2026-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0003_backfill_target_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionrun",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
