# Generated by Django 6.0.5 on 2026-05-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'پیش نویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('expired', 'منقضی شده'), ('archived', 'آرشیو')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'پیش نویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('expired', 'منقضی شده'), ('archived', 'آرشیو')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('active', 'فعال'), ('paused', 'متوقف'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('expired', 'منقضی شده'), ('archived', 'آرشیو')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('listed_sale_price', models.BigIntegerField(blank=True, null=True)),
                ('listed_deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('listed_rent_amount', models.BigIntegerField(blank=True, null=True)),
                ('listed_area', models.PositiveIntegerField(blank=True, null=True)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('leads_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
