# Generated by Django 5.2.16 on 2026-08-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('crm', '0001_initial'),
        ('listing', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, editable=False, max_length=30)),
                ('contract_type', models.CharField(choices=[('sale', 'مبایعه\u200cنامه'), ('rent', 'اجاره\u200cنامه'), ('mortgage', 'رهن'), ('agreement', 'توافق\u200cنامه')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('signed', 'امضا شده'), ('expired', 'منقضی'), ('canceled', 'لغو شده')], default='draft', max_length=20)),
                ('signed_by_customer', models.BooleanField(default=False)),
                ('signed_by_owner', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_histories', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='deals.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('deal_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage', 'رهن'), ('rent_mortgage', 'رهن و اجاره'), ('exchange', 'معاوضه')], max_length=30)),
                ('price', models.PositiveBigIntegerField()),
                ('deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('rent_amount', models.BigIntegerField(blank=True, null=True)),
                ('commission_amount', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در حال مذاکره'), ('agreement', 'توافق اولیه'), ('contracted', 'قرارداد بسته شده'), ('paid', 'تسویه شده'), ('canceled', 'لغو شده')], default='pending', max_length=30)),
                ('deal_date', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.customer')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='listing.listing')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='properties.property')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='deals.deal'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_by'], name='contracts_created_cc90a8_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['deal'], name='contracts_deal_id_bdd25b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['agency'], name='contracts_agency__d9e5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('agency', 'contract_number'), name='unique_contract_number_per_agency'),
        ),
    ]
