# Generated by Django 6.0.5 on 2026-05-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('sale', 'مبایعه نامه'), ('rent', 'اجاره نامه'), ('mortgage', 'رهن'), ('agreement', 'توافق نامه')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage', 'رهن'), ('rent_mortgage', 'رهن و اجاره'), ('exchange', 'معاوضه')], max_length=20)),
                ('price', models.BigIntegerField()),
                ('deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('rent_amount', models.BigIntegerField(blank=True, null=True)),
                ('commission_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در حال مذاکره'), ('agreement', 'توافق اولیه'), ('contracted', 'قرارداد بسته شده'), ('paid', 'تسویه شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
                ('deal_date', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.customer')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
