# Generated by Django 5.2.16 on 2026-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('active', 'فعال'), ('signed', 'امضا شده'), ('expired', 'منقضی'), ('canceled', 'لغو شده')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_number',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
    ]
