# Generated by Django 5.2.16 on 2026-08-09 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "features",
            },
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("national_id", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="accounts.agency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_code", models.CharField(editable=False, max_length=50)),
                ("title", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "deal_type",
                    models.CharField(
                        choices=[
                            ("sale", "فروش"),
                            ("rent", "اجاره"),
                            ("mortgage", "رهن کامل"),
                            ("exchange", "معاوضه"),
                        ],
                        max_length=30,
                    ),
                ),
                ("area", models.PositiveIntegerField()),
                ("floor", models.PositiveIntegerField(blank=True, null=True)),
                ("total_floors", models.PositiveIntegerField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(default=0)),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                ("bathrooms", models.PositiveSmallIntegerField(default=0)),
                ("parking_count", models.PositiveSmallIntegerField(default=0)),
                ("storage_count", models.PositiveSmallIntegerField(default=0)),
                ("orientation", models.CharField(blank=True, max_length=50)),
                ("condition", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price_per_meter", models.BigIntegerField(blank=True, null=True)),
                ("sale_price", models.BigIntegerField(blank=True, null=True)),
                ("mortgage_amount", models.BigIntegerField(blank=True, null=True)),
                ("deposit_amount", models.BigIntegerField(blank=True, null=True)),
                ("monthly_rent", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "فعال"),
                            ("reserved", "رزرو"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("archived", "بایگانی"),
                        ],
                        default="available",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.address",
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="accounts.agency",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="properties.owner",
                    ),
                ),
            ],
            options={
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.feature",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_features",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_features",
            },
        ),
        migrations.CreateModel(
            name="PropertyHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyStatusHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("available", "فعال"),
                            ("reserved", "رزرو"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("archived", "بایگانی"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("available", "فعال"),
                            ("reserved", "رزرو"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("archived", "بایگانی"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "db_table": "property_status_history",
            },
        ),
        migrations.AddConstraint(
            model_name="owner",
            constraint=models.UniqueConstraint(
                fields=("agency", "phone"), name="unique_owner_phone_per_agency"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="properties_status_e6008a_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["deal_type"], name="properties_deal_ty_b5accf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["owner"], name="properties_owner_i_921947_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["agent"], name="properties_agent_i_c4e85a_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_code"], name="properties_propert_a27a70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                fields=("agency", "property_code"),
                name="unique_property_code_per_agency",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyfeature",
            constraint=models.UniqueConstraint(
                fields=("property", "feature"), name="unique_property_feature"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyhistory",
            index=models.Index(
                fields=["property"], name="property_hi_propert_0f834d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyhistory",
            index=models.Index(
                fields=["created_at"], name="property_hi_created_6726f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertystatushistory",
            index=models.Index(
                fields=["property"], name="property_st_propert_35aa8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertystatushistory",
            index=models.Index(
                fields=["created_at"], name="property_st_created_2cd848_idx"
            ),
        ),
    ]
