# Generated by Django 5.2.16 on 2026-09-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_divar_neighborhood"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="divar_neighborhood",
        ),
    ]
