# Generated by Django 5.2.16 on 2026-07-19 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_create_by_alter_property_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertystatushistory',
            name='new_status',
            field=models.CharField(choices=[('available', 'فعال'), ('reserved', 'رزرو'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('archived', 'بایگانی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertystatushistory',
            name='old_status',
            field=models.CharField(choices=[('available', 'فعال'), ('reserved', 'رزرو'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('archived', 'بایگانی')], max_length=30),
        ),
        migrations.CreateModel(
            name='PropertyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='properties.property')),
            ],
            options={
                'db_table': 'property_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
