# Generated by Django 5.2.16 on 2026-09-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_seed_fardis_zones"),
        ("properties", "0003_remove_property_divar_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="divar_neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="locations.divarneighborhood",
            ),
        ),
    ]
