# Generated by Django 5.2.16 on 2026-09-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_divar_neighborhood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="deal_type",
            field=models.CharField(
                choices=[
                    ("exchange", "معاوضه"),
                    ("rent-residential", "اجارهٔ مسکونی"),
                    ("buy-residential", "فروش مسکونی"),
                    ("buy-commercial-property", "فروش اداری و تجاری"),
                    ("rent-commercial-property", "اجارهٔ اداری و تجاری"),
                ],
                max_length=30,
            ),
        ),
    ]
