# Generated by Django 5.2.16 on 2026-07-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertystatushistory_new_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
