import {
  PROPERTY_STATUS_CONFIG,
  PROPERTY_DEAL_TYPE_CONFIG,
} from "@/constants";

/**
 * Property Filters Config
 * Backend: properties.Property
 * 
 * Quick: search, deal_type, status, price_range, area, bedrooms
 * Advanced: owner, agent, location, physical, dates, features
 */

export const PROPERTY_QUICK_FILTERS = [
  {
    key: "search",
    label: "جستجو",
    type: "search",
    placeholder: "عنوان، کد ملک، توضیحات، آدرس...",
    fields: ["title", "property_code", "description", "address.full_text"],
    placement: "bar",
  },
  {
    key: "deal_type",
    label: "نوع معامله",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(PROPERTY_DEAL_TYPE_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "status",
    label: "وضعیت",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(PROPERTY_STATUS_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "price_range",
    label: "محدوده قیمت",
    type: "range",
    placement: "bar",
    min_key: "price_min",
    max_key: "price_max",
    step: 1_000_000,
    unit: "تومان",
    fields: ["sale_price", "monthly_rent", "mortgage_amount", "deposit_amount"],
  },
  {
    key: "area",
    label: "متراژ",
    type: "range",
    placement: "bar",
    min_key: "area_min",
    max_key: "area_max",
    step: 5,
    unit: "متر",
  },
  {
    key: "bedrooms",
    label: "اتاق خواب",
    type: "range",
    placement: "bar",
    min_key: "bedrooms_min",
    max_key: "bedrooms_max",
    step: 1,
    unit: "خواب",
  },
];

export const PROPERTY_ADVANCED_FILTERS = [
  {
    key: "property_type",
    label: "نوع ملک",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "APARTMENT", label: "آپارتمان" },
      { value: "VILLA", label: "ویلا" },
      { value: "LAND", label: "زمین" },
      { value: "COMMERCIAL", label: "تجاری" },
      { value: "OFFICE", label: "دفتر" },
      { value: "STORE", label: "مغازه" },
    ],
  },
  {
    key: "owner",
    label: "مالک",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: "/api/owner/list/",
    search_fields: ["full_name", "phone", "national_id"],
    optionLabel: "full_name",
    optionValue: "id",
  },
  {
    key: "agent",
    label: "مشاور",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: "/api/accounts/users/",
    search_fields: ["full_name", "phone"],
    optionLabel: "full_name",
    optionValue: "id",
  },
  {
    key: "province",
    label: "استان",
    type: "select",
    placement: "drawer",
    async: true,
    endpoint: "/api/province/list/",
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "city",
    label: "شهر",
    type: "select",
    placement: "drawer",
    async: true,
    endpoint: "/api/city/list/",
    depends_on: "province",
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "district",
    label: "منطقه",
    type: "select",
    placement: "drawer",
    async: true,
    endpoint: "/api/district/",
    depends_on: "city",
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "neighborhood",
    label: "محله",
    type: "select",
    placement: "drawer",
    async: true,
    endpoint: "/api/neighborhoods/",
    depends_on: "district",
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "age",
    label: "سن بنا",
    type: "range",
    placement: "drawer",
    min_key: "age_min",
    max_key: "age_max",
    step: 1,
    unit: "سال",
  },
  {
    key: "floor",
    label: "طبقه",
    type: "range",
    placement: "drawer",
    min_key: "floor_min",
    max_key: "floor_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "total_floors",
    label: "تعداد طبقات",
    type: "range",
    placement: "drawer",
    min_key: "total_floors_min",
    max_key: "total_floors_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "bathrooms",
    label: "سرویس بهداشتی",
    type: "range",
    placement: "drawer",
    min_key: "bathrooms_min",
    max_key: "bathrooms_max",
    step: 1,
    unit: "",
  },
  {
    key: "parking",
    label: "پارکینگ",
    type: "range",
    placement: "drawer",
    min_key: "parking_min",
    max_key: "parking_max",
    step: 1,
    unit: "",
  },
  {
    key: "storage",
    label: "انباری",
    type: "range",
    placement: "drawer",
    min_key: "storage_min",
    max_key: "storage_max",
    step: 1,
    unit: "",
  },
  {
    key: "orientation",
    label: "جهت",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "NORTH", label: "شمال" },
      { value: "SOUTH", label: "جنوب" },
      { value: "EAST", label: "شرق" },
      { value: "WEST", label: "غرب" },
      { value: "NORTHEAST", label: "شمال شرق" },
      { value: "NORTHWEST", label: "شمال غرب" },
      { value: "SOUTHEAST", label: "جنوب شرق" },
      { value: "SOUTHWEST", label: "جنوب غرب" },
    ],
  },
  {
    key: "condition",
    label: "وضعیت ساختمان",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "EXCELLENT", label: "عالی" },
      { value: "GOOD", label: "خوب" },
      { value: "AVERAGE", label: "متوسط" },
      { value: "NEEDS_REPAIR", label: "نیاز به بازسازی" },
      { value: "OLD", label: "قدیمی" },
    ],
  },
  {
    key: "price_per_meter",
    label: "قیمت هر متر",
    type: "range",
    placement: "drawer",
    min_key: "ppm_min",
    max_key: "ppm_max",
    step: 100_000,
    unit: "تومان",
  },
  {
    key: "mortgage_amount",
    label: "مبلغ رهن",
    type: "range",
    placement: "drawer",
    min_key: "mortgage_min",
    max_key: "mortgage_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "deposit_amount",
    label: "مبلغ ودیعه",
    type: "range",
    placement: "drawer",
    min_key: "deposit_min",
    max_key: "deposit_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "monthly_rent",
    label: "اجاره ماهیانه",
    type: "range",
    placement: "drawer",
    min_key: "rent_min",
    max_key: "rent_max",
    step: 500_000,
    unit: "تومان",
  },
  {
    key: "has_owner",
    label: "دارای مالک",
    type: "toggle",
    placement: "drawer",
    filter: (row) => !!row.owner,
  },
  {
    key: "has_agent",
    label: "دارای مشاور",
    type: "toggle",
    placement: "drawer",
    filter: (row) => !!row.agent,
  },
  {
    key: "created_at",
    label: "تاریخ ثبت",
    type: "date_range",
    placement: "drawer",
    from_key: "created_from",
    to_key: "created_to",
  },
  {
    key: "updated_at",
    label: "آخرین بروزرسانی",
    type: "date_range",
    placement: "drawer",
    from_key: "updated_from",
    to_key: "updated_to",
  },
];

export const PROPERTY_ALL_FILTERS = [...PROPERTY_QUICK_FILTERS, ...PROPERTY_ADVANCED_FILTERS];