export const PROPERTY_FILTERS = [
  {
    key: "search",
    type: "search",
    label: "جستجو",
    placeholder: "عنوان، کد ملک، توضیحات...",
  },
  {
    key: "status",
    type: "select",
    label: "وضعیت",
    optionsKey: "statuses",
    options: [
      { value: "available", label: "موجود" },
      { value: "reserved", label: "رزرو شده" },
      { value: "sold", label: "فروخته شده" },
      { value: "rented", label: "اجاره داده شده" },
      { value: "unavailable", label: "غیرقابل دسترس" },
      { value: "draft", label: "پیش نویس" },
    ],
  },
  {
    key: "property_type",
    type: "select",
    label: "نوع ملک",
    optionsKey: "propertyTypes",
    options: [
      { value: "apartment", label: "آپارتمان" },
      { value: "villa", label: "ویلا" },
      { value: "land", label: "زمین" },
      { value: "commercial", label: "تجاری" },
      { value: "office", label: "اداری" },
      { value: "store", label: "مغازه" },
      { value: "workshop", label: "کارگاه" },
    ],
  },
  {
    key: "deal_type",
    type: "select",
    label: "نوع معامله",
    optionsKey: "dealTypes",
    options: [
      { value: "sale", label: "فروش" },
      { value: "rent", label: "اجاره" },
      { value: "mortgage", label: "رهن کامل" },
    ],
  },
  {
    key: "area",
    type: "range",
    label: "متراژ",
    unit: "متر",
    min: 0,
    max: 10000,
    step: 10,
  },
  {
    key: "created_by",
    type: "select",
    label: "ثبت کننده",
    optionsKey: "users",
    options: [
      { value: "1", label: "مدیریت ملک جو" },
      { value: "2", label: "کارشناس ۱ - علی رضایی" },
      { value: "3", label: "کارشناس ۲ - سارا محمدی" },
      { value: "4", label: "کارشناس ۳ - حسن کریمی" },
    ],
  },
];