import {
  PROPERTY_STATUS_CONFIG,
  PROPERTY_DEAL_TYPE_CONFIG,
} from "@/features/properties/config";
import { API_ENDPOINTS } from "@/constants/apiEndpoints";

/**
 * Property Filters Config
 * Backend: properties.Property
 *
 * Quick: search, deal_type, status, price_range, area, bedrooms
 * Advanced: owner, agent, location, physical, dates, features
 */

export const PROPERTY_QUICK_FILTERS = [
  {
    key: "search",
    label: "جستجو",
    type: "search",
    placeholder: "عنوان، کد ملک، توضیحات، آدرس...",
    fields: ["title", "property_code", "description", "address.full_text"],
    placement: "bar",
  },
  {
    key: "deal_type",
    label: "نوع معامله",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(PROPERTY_DEAL_TYPE_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "status",
    label: "وضعیت",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(PROPERTY_STATUS_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "price_range",
    label: "محدوده قیمت",
    type: "range",
    placement: "bar",
    min: 0,
    max: 100_000_000_000,
    min_key: "price_min",
    max_key: "price_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "province",
    label: "استان",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: API_ENDPOINTS.LOCATIONS.PROVINCES.LIST.url,
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "city",
    label: "شهر",
    type: "search_select",
    placement: "drawer",
    async: true,
    depends_on: "province",
    endpoint: API_ENDPOINTS.LOCATIONS.CITIES.LIST.url,
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "district",
    label: "منطقه",
    type: "search_select",
    placement: "drawer",
    async: true,
    depends_on: "city",
    endpoint: API_ENDPOINTS.LOCATIONS.DISTRICTS.LIST.url,
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "neighborhood",
    label: "محله",
    type: "search_select",
    placement: "drawer",
    async: true,
    depends_on: "district",
    endpoint: API_ENDPOINTS.LOCATIONS.NEIGHBORHOODS.LIST.url,
    optionLabel: "name",
    optionValue: "id",
  },
];

export const PROPERTY_ADVANCED_FILTERS = [
  {
    key: "zone",
    label: "زون",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: `${API_ENDPOINTS.LOCATIONS.ZONES.LIST.url}?active=true`,
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "divar_neighborhood",
    label: "محلهٔ دیوار",
    type: "search_select",
    placement: "drawer",
    async: true,
    depends_on: "zone",
    endpoint: `${API_ENDPOINTS.LOCATIONS.DIVAR_NEIGHBORHOODS.LIST.url}?zone={zone}&active=true`,
    optionLabel: "name",
    optionValue: "id",
  },
   // ─── اشخاص ───
  {
    key: "owner",
    label: "مالک",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: API_ENDPOINTS.OWNERS.LIST.url,
    search_fields: ["full_name", "phone", "national_id"],
    optionLabel: "full_name",
    optionValue: "id",
  },
  {
    key: "agent",
    label: "مشاور",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: API_ENDPOINTS.ACCOUNTS.USERS.LIST.url,
    search_fields: ["full_name", "phone"],
    optionLabel: "full_name",
    optionValue: "id",
  },
  // ─── مشخصات ملک ───
  {
    key: "property_type",
    label: "نوع ملک",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "آپارتمان", label: "آپارتمان" },
      { value: "ویلا", label: "ویلا" },
      { value: "زمین", label: "زمین" },
      { value: "تجاری", label: "تجاری" },
      { value: "دفتر", label: "دفتر" },
      { value: "مغازه", label: "مغازه" },
    ],
  },
  
  // ─── قیمت ───
  {
    key: "price_per_meter",
    label: "قیمت هر متر",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 100_000_000,
    min_key: "ppm_min",
    max_key: "ppm_max",
    step: 100_000,
    unit: "تومان",
  },
  {
    key: "mortgage_amount",
    label: "مبلغ رهن",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 10_000_000_000,
    min_key: "mortgage_min",
    max_key: "mortgage_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "deposit_amount",
    label: "مبلغ ودیعه",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 10_000_000_000,
    min_key: "deposit_min",
    max_key: "deposit_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "monthly_rent",
    label: "اجاره ماهیانه",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 500_000_000,
    min_key: "rent_min",
    max_key: "rent_max",
    step: 500_000,
    unit: "تومان",
  },
  {
    key: "area",
    label: "متراژ",
    type: "range",
    placement: "bar",
    min: 0,
    max: 500,
    min_key: "area_min",
    max_key: "area_max",
    step: 5,
    unit: "متر",
  },
  {
    key: "bedrooms",
    label: "اتاق خواب",
    type: "range",
    placement: "bar",
    min: 0,
    max: 10,
    min_key: "bedrooms_min",
    max_key: "bedrooms_max",
    step: 1,
    unit: "اتاق",
  },
  
  
  {
    key: "age",
    label: "سن بنا",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 50,
    min_key: "age_min",
    max_key: "age_max",
    step: 1,
    unit: "سال",
  },
  {
    key: "floor",
    label: "طبقه",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 30,
    min_key: "floor_min",
    max_key: "floor_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "total_floors",
    label: "تعداد طبقات",
    type: "range",
    placement: "drawer",
    min: 1,
    max: 30,
    min_key: "total_floors_min",
    max_key: "total_floors_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "bathrooms",
    label: "سرویس بهداشتی",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 5,
    min_key: "bathrooms_min",
    max_key: "bathrooms_max",
    step: 1,
    unit: "",
  },
  {
    key: "parking",
    label: "پارکینگ",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 5,
    min_key: "parking_min",
    max_key: "parking_max",
    step: 1,
    unit: "",
  },
  {
    key: "storage",
    label: "انباری",
    type: "range",
    placement: "drawer",
    min: 0,
    max: 5,
    min_key: "storage_min",
    max_key: "storage_max",
    step: 1,
    unit: "",
  },
  {
    key: "orientation",
    label: "جهت",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "north", label: "شمال" },
      { value: "south", label: "جنوب" },
      { value: "east", label: "شرق" },
      { value: "west", label: "غرب" },
      { value: "northeast", label: "شمال شرق" },
      { value: "northwest", label: "شمال غرب" },
      { value: "southeast", label: "جنوب شرق" },
      { value: "southwest", label: "جنوب غرب" },
    ],
  },
  {
    key: "condition",
    label: "وضعیت ساختمان",
    type: "multi_select",
    placement: "drawer",
    options: [
      { value: "excellent", label: "عالی" },
      { value: "good", label: "خوب" },
      { value: "average", label: "متوسط" },
      { value: "needs_renovation", label: "نیاز به بازسازی" },
      { value: "old", label: "قدیمی" },
    ],
  },

  // ─── Booleans ───
  {
    key: "has_owner",
    label: "دارای مالک",
    type: "toggle",
    placement: "drawer",
  },
  {
    key: "has_agent",
    label: "دارای مشاور",
    type: "toggle",
    placement: "drawer",
  },

  {
    key: "created_at",
    label: "تاریخ ثبت",
    type: "date_range",
    placement: "drawer",
    from_key: "created_from",
    to_key: "created_to",
  },
  {
    key: "updated_at",
    label: "آخرین بروزرسانی",
    type: "date_range",
    placement: "drawer",
    from_key: "updated_from",
    to_key: "updated_to",
  },
];

export const PROPERTY_ALL_FILTERS = [
  ...PROPERTY_QUICK_FILTERS,
  ...PROPERTY_ADVANCED_FILTERS,
];
