/**
 * Create/Edit Property Form
 * Multi-tab: basic, location, specs, price, owner_agent
 */
export const PROPERTY_FORM = {
  title: "پرونده ملک",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات پایه",
      icon: "Home",
      fields: [
        {
          key: "property_code",
          label: "کد ملک",
          type: "text",
          readOnly: true,
          span: 6,
        },
        {
          key: "title",
          label: "عنوان ملک",
          type: "text",
          required: true,
          placeholder: "مثلاً آپارتمان ۱۲۰ متری عظیمیه",
          validation: { required: "عنوان ملک الزامی است" },
          span: 6,
        },
        {
          key: "deal_type",
          label: "نوع معامله",
          type: "select",
          required: true,
          placeholder: "انتخاب نوع",
          options: [
            { value: "sale", label: "فروش" },
            { value: "rent", label: "اجاره" },
            { value: "mortgage", label: "رهن" },
            { value: "exchange", label: "معاوضه" },
          ],
          validation: { required: "نوع معامله الزامی است" },
          span: 6,
        },
        {
          key: "status",
          label: "وضعیت",
          type: "select",
          required: true,
          placeholder: "انتخاب وضعیت",
          options: [
            { value: "available", label: "در دسترس" },
            { value: "reserved", label: "رزرو شده" },
            { value: "sold", label: "فروخته شده" },
            { value: "rented", label: "اجاره داده شده" },
            { value: "archived", label: "آرشیو" },
          ],
          defaultValue: "available",
          validation: { required: "وضعیت الزامی است" },
          span: 6,
        },
        {
          key: "property_type",
          label: "نوع ملک",
          type: "select",
          required: false,
          placeholder: "انتخاب نوع ملک",
          options: [
            { value: "APARTMENT", label: "آپارتمان" },
            { value: "VILLA", label: "ویلا" },
            { value: "LAND", label: "زمین" },
            { value: "COMMERCIAL", label: "تجاری" },
            { value: "OFFICE", label: "دفتر" },
            { value: "STORE", label: "مغازه" },
          ],
          span: 6,
        },
        {
          key: "owner",
          label: "مالک",
          type: "search_select",
          required: true,
          placeholder: "انتخاب مالک...",
          asyncSource: "/api/owner/list",
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          span: 6,
        },
        {
          key: "agent",
          label: "مشاور",
          type: "search_select",
          required: false,
          placeholder: "انتخاب مشاور...",
          asyncSource: "/api/accounts/users/",
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          span: 6,
        },
        {
          key: "description",
          label: "توضیحات",
          type: "textarea",
          required: false,
          placeholder: "توضیحات تکمیلی ملک...",
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "location",
      label: "موقعیت مکانی",
      icon: "MapPin",
      fields: [
        // TODO: check in UI
        {
          key: "address",
          label: "آدرس ثبت شده",
          type: "search_select",
          required: false,
          placeholder: "انتخاب آدرس...",
          asyncSource: "/api/addresses/",
          displayField: "full_text",
          span: 12,
        },
      ],
    },
    {
      key: "specs",
      label: "مشخصات فنی",
      icon: "Ruler",
      fields: [
        {
          key: "area",
          label: "متراژ (متر مربع)",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱۲۰",
          min: 0,
          span: 6,
        },
        {
          key: "age",
          label: "سال ساخت",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱۳۹۸",
          min: 1300,
          max: 1500,
          span: 6,
        },
        {
          key: "bedrooms",
          label: "تعداد اتاق خواب",
          type: "number",
          required: false,
          placeholder: "مثلاً ۲",
          min: 0,
          span: 6,
        },
        {
          key: "bathrooms",
          label: "تعداد سرویس بهداشتی",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱",
          min: 0,
          span: 6,
        },
        {
          key: "floor",
          label: "شماره طبقه",
          type: "number",
          required: false,
          placeholder: "مثلاً ۳",
          span: 6,
        },
        {
          key: "total_floors",
          label: "تعداد کل طبقات",
          type: "number",
          required: false,
          placeholder: "مثلاً ۵",
          span: 6,
        },
        {
          key: "parking_count",
          label: "تعداد پارکینگ",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱",
          min: 0,
          span: 6,
        },
        {
          key: "storage_count",
          label: "تعداد انباری",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱",
          min: 0,
          span: 6,
        },
        {
          key: "orientation",
          label: "جهت",
          // NOTE: backend orientation is CharField (single string), not array.
          // Changed from multi_select → select to match backend contract.
          type: "select",
          required: false,
          placeholder: "انتخاب جهت",
          options: [
            { value: "north", label: "شمالی" },
            { value: "south", label: "جنوبی" },
            { value: "east", label: "شرقی" },
            { value: "west", label: "غربی" },
            { value: "northeast", label: "شمال شرقی" },
            { value: "northwest", label: "شمال غربی" },
            { value: "southeast", label: "جنوب شرقی" },
            { value: "southwest", label: "جنوب غربی" },
          ],
          span: 6,
        },
        {
          key: "condition",
          label: "وضعیت ساختمان",
          type: "select",
          required: false,
          placeholder: "انتخاب وضعیت",
          options: [
            { value: "excellent", label: "عالی" },
            { value: "good", label: "خوب" },
            { value: "average", label: "متوسط" },
            { value: "needs_renovation", label: "نیاز به بازسازی" },
            { value: "old", label: "قدیمی" },
          ],
          span: 6,
        },
      ],
    },
    {
      key: "sale_price",
      label: "قیمت و مالی",
      icon: "Banknote",
      fields: [
        {
          key: "sale_price",
          label: "قیمت کل (تومان)",
          type: "price",
          required: false,
          placeholder: "مثلاً ۵,۰۰۰,۰۰۰,۰۰۰",
          condition: (values) => values.deal_type === "sale",
          span: 12,
        },
        {
          key: "deposit_amount",
          label: "ودیعه (تومان)",
          type: "price",
          required: false,
          placeholder: "مثلاً ۵۰۰,۰۰۰,۰۰۰",
          condition: (values) => values.deal_type === "rent",
          span: 6,
        },
        {
          key: "mortgage_amount",
          label: "مبلغ رهن (تومان)",
          type: "price",
          required: false,
          placeholder: "مثلاً ۵۰۰,۰۰۰,۰۰۰",
          condition: (values) =>
            values.deal_type === "mortgage" || values.deal_type === "rent",
          span: 6,
        },
        {
          key: "monthly_rent",
          label: "اجاره ماهانه (تومان)",
          type: "price",
          required: false,
          placeholder: "مثلاً ۱۵,۰۰۰,۰۰۰",
          condition: (values) => values.deal_type === "rent",
          span: 6,
        },
        {
          key: "price_per_meter",
          label: "قیمت هر متر (تومان)",
          type: "price",
          required: false,
          placeholder: "محاسبه خودکار",
          computed: (values) =>
            values.sale_price && values.area
              ? Math.round(values.sale_price / values.area)
              : null,
          readOnly: true,
          span: 6,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره ملک", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};

/**
 * Change Property Status Form
 * DISABLED: No backend endpoint for bulk status change exists.
 * Re-enable when backend implements: PUT /api/property/bulk-change-status/
 */
// export const CHANGE_PROPERTY_STATUS_FORM = { ... };

/**
 * Assign Agent Form
 * DISABLED: No backend endpoint for bulk agent assignment exists.
 * Re-enable when backend implements: PUT /api/property/bulk-assign-agent/
 */
// export const ASSIGN_AGENT_FORM = { ... };

/**
 * Promote Listing → Property Form
 * Multi-tab: listing info (read-only), property data, owner, price
 * Auto-fills from listing data
 */
export const PROMOTE_LISTING_FORM = {
  title: "تبدیل آگهی به ملک",
  description:
    "آگهی انتخاب‌شده به پرونده ملک تبدیل می‌شود — اطلاعات قابل ویرایش هستند",
  tabs: [
    {
      key: "listing_info",
      label: "اطلاعات آگهی",
      icon: "FileText",
      fields: [
        {
          key: "listing_title",
          label: "عنوان آگهی",
          type: "text",
          required: false,
          autoFill: { source: "listing", field: "title", readOnly: true },
          span: 12,
        },
        {
          key: "listing_source",
          label: "منبع",
          type: "text",
          required: false,
          autoFill: { source: "listing", field: "source", readOnly: true },
          span: 6,
        },
        {
          key: "listing_url",
          label: "لینک منبع",
          type: "link",
          required: false,
          autoFill: { source: "listing", field: "url", readOnly: true },
          span: 6,
        },
        {
          key: "listing_deal_type",
          label: "نوع معامله آگهی",
          type: "text",
          required: false,
          autoFill: { source: "listing", field: "deal_type", readOnly: true },
          span: 6,
        },
        {
          key: "listing_price",
          label: "قیمت آگهی",
          type: "price",
          required: false,
          autoFill: { source: "listing", field: "price", readOnly: true },
          span: 6,
        },
        {
          key: "listing_area",
          label: "متراژ آگهی",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "area", readOnly: true },
          span: 6,
        },
        {
          key: "listing_age",
          label: "سال ساخت آگهی",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "age", readOnly: true },
          span: 6,
        },
        {
          key: "listing_bedrooms",
          label: "تعداد اتاق آگهی",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "bedrooms", readOnly: true },
          span: 6,
        },
        {
          key: "listing_description",
          label: "توضیحات آگهی",
          type: "textarea",
          required: false,
          autoFill: { source: "listing", field: "description", readOnly: true },
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "property_data",
      label: "اطلاعات ملک نهایی",
      icon: "Home",
      fields: [
        {
          key: "property_code",
          label: "کد ملک",
          type: "text",
          required: true,
          placeholder: "مثلاً PR-1403-001",
          validation: { required: "کد ملک الزامی است" },
          span: 6,
        },
        {
          key: "title",
          label: "عنوان ملک",
          type: "text",
          required: true,
          placeholder: "عنوان نهایی ملک",
          autoFill: { source: "listing", field: "title", readOnly: false },
          validation: { required: "عنوان ملک الزامی است" },
          span: 6,
        },
        {
          key: "deal_type",
          label: "نوع معامله",
          type: "select",
          required: true,
          options: [
            { value: "sale", label: "فروش" },
            { value: "rent", label: "اجاره" },
            { value: "presale", label: "پیش‌فروش" },
          ],
          autoFill: { source: "listing", field: "deal_type", readOnly: false },
          validation: { required: "نوع معامله الزامی است" },
          span: 6,
        },
        {
          key: "status",
          label: "وضعیت",
          type: "select",
          required: true,
          options: [
            { value: "available", label: "در دسترس" },
            { value: "reserved", label: "رزرو شده" },
          ],
          defaultValue: "available",
          validation: { required: "وضعیت الزامی است" },
          span: 6,
        },
        {
          key: "price",
          label: "قیمت نهایی (تومان)",
          type: "price",
          required: false,
          placeholder: "قیمت نهایی توافق‌شده",
          autoFill: { source: "listing", field: "price", readOnly: false },
          span: 6,
        },
        {
          key: "area",
          label: "متراژ نهایی",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "area", readOnly: false },
          span: 6,
        },
        {
          key: "age",
          label: "سال ساخت",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "age", readOnly: false },
          span: 6,
        },
        {
          key: "bedrooms",
          label: "تعداد اتاق",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "bedrooms", readOnly: false },
          span: 6,
        },
        {
          key: "floor",
          label: "شماره طبقه",
          type: "number",
          required: false,
          autoFill: { source: "listing", field: "floor", readOnly: false },
          span: 6,
        },
        {
          key: "total_floors",
          label: "تعداد طبقات",
          type: "number",
          required: false,
          autoFill: {
            source: "listing",
            field: "total_floors",
            readOnly: false,
          },
          span: 6,
        },
        {
          key: "description",
          label: "توضیحات",
          type: "textarea",
          required: false,
          autoFill: {
            source: "listing",
            field: "description",
            readOnly: false,
          },
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "owner",
      label: "مالک",
      icon: "User",
      fields: [
        {
          key: "owner",
          label: "مالک",
          type: "search_select",
          required: false,
          placeholder: "جستجوی مالک...",
          asyncSource: "/api/customers/",
          searchFields: ["full_name", "phone", "national_id"],
          displayField: "full_name",
          autoFill: {
            source: "listing",
            field: "owner_snapshot",
            readOnly: false,
          },
          span: 12,
        },
        {
          key: "create_new_owner",
          label: "مالک جدید ثبت کنم",
          type: "checkbox",
          required: false,
          defaultValue: false,
          span: 12,
        },
      ],
    },
    {
      key: "location",
      label: "آدرس",
      icon: "MapPin",
      fields: [
        {
          key: "province",
          label: "استان",
          type: "search_select",
          required: true,
          placeholder: "انتخاب استان",
          asyncSource: "/api/province/list/",
          displayField: "name",
          validation: { required: "استان الزامی است" },
          span: 6,
        },
        {
          key: "city",
          label: "شهر",
          type: "search_select",
          required: true,
          placeholder: "انتخاب شهر",
          dependsOn: "province",
          asyncSource: "/api/city/list/",
          displayField: "name",
          validation: { required: "شهر الزامی است" },
          span: 6,
        },
        {
          key: "district",
          label: "منطقه",
          type: "search_select",
          required: false,
          placeholder: "انتخاب منطقه",
          dependsOn: "city",
          asyncSource: "/api/district/",
          displayField: "name",
          span: 6,
        },
        {
          key: "neighborhood",
          label: "محله",
          type: "search_select",
          required: false,
          placeholder: "انتخاب محله",
          dependsOn: "district",
          asyncSource: "/api/neighborhoods/",
          displayField: "name",
          span: 6,
        },
        {
          key: "street",
          label: "خیابان",
          type: "text",
          required: false,
          span: 6,
        },
        {
          key: "alley",
          label: "کوچه",
          type: "text",
          required: false,
          span: 6,
        },
        {
          key: "plaque",
          label: "پلاک",
          type: "text",
          required: false,
          span: 6,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "تبدیل به ملک", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};
