# Generated by Django 5.2.16 on 2026-08-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listing', '0001_initial'),
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('buyer', 'خریدار'), ('seller', 'فروشنده'), ('tenant', 'مستاجر'), ('landlord', 'موجر'), ('investor', 'سرمایه گذار')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'جدید'), ('contacted', 'تماس گرفته شده'), ('interested', 'علاقه مند'), ('negotiation', 'مذاکره'), ('closed', 'بسته شده'), ('lost', 'از دست رفته')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.agency')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage', 'رهن')], max_length=20)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('budget_min', models.BigIntegerField(blank=True, null=True)),
                ('budget_max', models.BigIntegerField(blank=True, null=True)),
                ('area_min', models.PositiveIntegerField(blank=True, null=True)),
                ('area_max', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='crm.customer')),
                ('neighborhoods', models.ManyToManyField(blank=True, to='locations.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.agency')),
            ],
            options={
                'db_table': 'customer_tags',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='crm.tag'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('incoming', 'ورودی'), ('outgoing', 'خروجی')], max_length=20)),
                ('result', models.CharField(choices=[('answered', 'پاسخ داده شد'), ('no_answer', 'پاسخ نداد'), ('busy', 'مشغول'), ('interested', 'علاقه\u200cمند'), ('not_interested', 'عدم تمایل'), ('follow_up', 'نیاز به پیگیری'), ('visit_booked', 'بازدید ثبت شد')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('call_duration', models.PositiveIntegerField(default=0)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_done', models.BooleanField(default=False)),
                ('record_file', models.FileField(blank=True, null=True, upload_to='calls/')),
                ('called_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='accounts.agency')),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_calls', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='listing.listing')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='properties.property')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.customer')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-called_at'],
                'indexes': [models.Index(fields=['customer'], name='call_logs_custome_41ca8a_idx'), models.Index(fields=['handled_by'], name='call_logs_handled_e92bac_idx'), models.Index(fields=['called_at'], name='call_logs_called__1742a3_idx'), models.Index(fields=['result'], name='call_logs_result_c0d8f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'برنامه ریزی شده'), ('confirmed', 'تایید شده'), ('completed', 'انجام شده'), ('canceled', 'لغو شده'), ('no_show', 'عدم حضور مشتری')], default='scheduled', max_length=20)),
                ('customer_feedback', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_visits', to='accounts.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property')),
            ],
            options={
                'db_table': 'property_visits',
                'ordering': ['-visit_date'],
                'indexes': [models.Index(fields=['agency', 'status'], name='property_vi_agency__9fdf77_idx'), models.Index(fields=['visit_date'], name='property_vi_visit_d_afaa22_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('call', 'تماس'), ('visit', 'بازدید'), ('follow_up', 'پیگیری'), ('other', 'سایر')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.agency')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['agency', 'status'], name='reminders_agency__f8df87_idx'), models.Index(fields=['due_at'], name='reminders_due_at_624020_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('agency', 'name'), name='unique_tag_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('agency', 'phone'), name='unique_customer_phone_per_agency'),
        ),
    ]
