# Generated by Django 5.2.16 on 2026-07-28 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_type', models.CharField(choices=[('buyer', 'خریدار'), ('renter', 'مستاجر'), ('investor', 'سرمایه گذار')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('incoming', 'ورودی'), ('outgoing', 'خروجی')], max_length=20)),
                ('result', models.CharField(choices=[('answered', 'پاسخ داده شد'), ('no_answer', 'پاسخ نداد'), ('busy', 'مشغول'), ('interested', 'علاقه مند'), ('not_interested', 'عدم تمایل'), ('follow_up', 'نیاز به پیگیری'), ('visit_booked', 'بازدید ثبت شد')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('call_duration', models.PositiveIntegerField(default=0)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_calls', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.listing')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.customer')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('budget_min', models.BigIntegerField(blank=True, null=True)),
                ('budget_max', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='crm.customer')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'برنامه ریزی شده'), ('completed', 'انجام شده'), ('canceled', 'لغو شده'), ('no_show', 'عدم حضور مشتری')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_visits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.customer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='properties.property')),
            ],
            options={
                'db_table': 'property_visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['due_at'],
            },
        ),
    ]
