# Generated by Django 5.2.16 on 2026-09-08 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("properties", "0005_alter_property_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="properties.owner",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="crm.customer",
            ),
        ),
    ]
