import { API_ENDPOINTS } from "@/constants/apiEndpoints";

export const CUSTOMER_PREFERENCE_FORM = {
  title: "ترجیحات ملک",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات پایه",
      icon: "Home",
      fields: [
        {
          key: "customer",
          label: "مشتری",
          type: "search_select",
          required: true,
          placeholder: "جستجوی مشتری...",
          asyncSource: API_ENDPOINTS.CUSTOMERS.LIST.url,
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          validation: { required: "انتخاب مشتری الزامی است" },
          span: 12,
        },
        {
          key: "deal_type",
          label: "نوع معامله",
          type: "select",
          required: true,
          placeholder: "انتخاب نوع",
          options: [
            { value: "sale", label: "فروش" },
            { value: "rent", label: "اجاره" },
            { value: "mortgage", label: "رهن" },
          ],
          validation: { required: "نوع معامله الزامی است" },
          span: 6,
        },
        {
          key: "property_type",
          label: "نوع ملک",
          type: "text",
          required: false,
          placeholder: "آپارتمان، ویلایی، اداری...",
          span: 6,
        },
      ],
    },
    {
      key: "budget",
      label: "بودجه و متراژ",
      icon: "Banknote",
      fields: [
        {
          key: "budget_min",
          label: "حداقل بودجه (تومان)",
          type: "number",
          required: false,
          placeholder: "مثلاً 5000000000",
          span: 6,
        },
        {
          key: "budget_max",
          label: "حداکثر بودجه (تومان)",
          type: "number",
          required: false,
          placeholder: "مثلاً 10000000000",
          span: 6,
        },
        {
          key: "area_min",
          label: "حداقل متراژ (متر مربع)",
          type: "number",
          required: false,
          placeholder: "مثلاً 80",
          span: 6,
        },
        {
          key: "area_max",
          label: "حداکثر متراژ (متر مربع)",
          type: "number",
          required: false,
          placeholder: "مثلاً 150",
          span: 6,
        },
        {
          key: "bedrooms",
          label: "تعداد اتاق خواب",
          type: "number",
          required: false,
          placeholder: "مثلاً 2",
          min: 0,
          max: 10,
          span: 6,
        },
      ],
    },
    {
      key: "location",
      label: "محله‌های مورد نظر",
      icon: "MapPin",
      fields: [
        {
          key: "neighborhoods",
          label: "محله‌ها",
          type: "multi_select",
          required: false,
          placeholder: "انتخاب محله‌ها...",
          asyncSource: API_ENDPOINTS.LOCATIONS.NEIGHBORHOODS.LIST.url,
          searchFields: ["name"],
          displayField: "name",
          span: 12,
        },
        {
          key: "notes",
          label: "یادداشت‌ها",
          type: "textarea",
          required: false,
          placeholder: "توضیحات تکمیلی درباره ترجیحات مشتری...",
          rows: 3,
          span: 12,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره ترجیحات", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};
