# Generated by Django 6.0.5 on 2026-05-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=30)),
                ('deal_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage', 'رهن کامل'), ('exchange', 'معاوضه')], max_length=30)),
                ('area', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('parking_count', models.PositiveSmallIntegerField(default=0)),
                ('storage_count', models.PositiveSmallIntegerField(default=0)),
                ('orientation', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_per_meter', models.BigIntegerField(blank=True, null=True)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('mortgage_amount', models.BigIntegerField(blank=True, null=True)),
                ('deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('monthly_rent', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'فعال'), ('reserved', 'رزرو'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('archived', 'بایگانی')], default='available', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.address')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.owner')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/')),
                ('media_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدئو')], max_length=20)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property')),
            ],
            options={
                'db_table': 'property_media',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.feature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='properties.property')),
            ],
            options={
                'db_table': 'property_features',
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
