# Generated by Django 6.0.5 on 2026-09-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivarNeighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('normalized_name', models.CharField(max_length=150)),
                ('source', models.CharField(default='divar', editable=False, max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'divar_neighborhoods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='unique_nonempty_city_slug'),
        ),
        migrations.AddField(
            model_name='divarneighborhood',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divar_neighborhoods', to='locations.city'),
        ),
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='locations.city'),
        ),
        migrations.AddField(
            model_name='divarneighborhood',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divar_neighborhoods', to='locations.zone'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='unique_zone_name_per_city'),
        ),
        migrations.AddIndex(
            model_name='divarneighborhood',
            index=models.Index(fields=['city', 'zone', 'active'], name='divar_neigh_city_id_01fb85_idx'),
        ),
        migrations.AddConstraint(
            model_name='divarneighborhood',
            constraint=models.UniqueConstraint(fields=('city', 'normalized_name'), name='unique_divar_neighborhood_city_normalized_name'),
        ),
    ]
