import { API_ENDPOINTS } from "@/constants/apiEndpoints";

export const CALL_FORM = {
  // title: "تماس",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات تماس",
      icon: "Phone",
      fields: [
        {
          key: "customer",
          label: "مشتری / تماس‌گیرنده",
          type: "search_select",
          required: true,
          placeholder: "جستجوی مشتری...",
          asyncSource: API_ENDPOINTS.CUSTOMERS.LIST.url,
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          validation: { required: "انتخاب مشتری الزامی است" },
          span: 12,
        },
        {
          key: "call_type",
          label: "نوع تماس",
          type: "select",
          required: true,
          options: [
            { value: "incoming", label: "ورودی" },
            { value: "outgoing", label: "خروجی" },
          ],
          defaultValue: "outgoing",
          validation: { required: "نوع تماس الزامی است" },
          span: 6,
        },
        {
          key: "called_at",
          label: "زمان تماس",
          type: "datetime",
          required: true,
          defaultValue: "now",
          validation: { required: "زمان تماس الزامی است" },
          span: 6,
        },
        {
          key: "call_duration",
          label: "مدت تماس (ثانیه)",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱۲۰",
          min: 0,
          span: 6,
        },
        {
          key: "result",
          label: "نتیجه تماس",
          type: "select",
          required: true,
          placeholder: "انتخاب نتیجه",
          options: [
            { value: "answered", label: "پاسخ داده" },
            { value: "no_answer", label: "بدون پاسخ" },
            { value: "busy", label: "مشغول" },
            { value: "interested", label: "علاقه‌مند" },
            { value: "not_interested", label: "عدم علاقه" },
            { value: "follow_up", label: "نیاز به پیگیری" },
            { value: "visit_booked", label: "قرار بازدید" },
          ],
          validation: { required: "نتیجه تماس الزامی است" },
          span: 6,
        },
        {
          key: "note",
          label: "یادداشت",
          type: "textarea",
          required: false,
          placeholder: "جزئیات تماس...",
          rows: 2,
          span: 12,
        },
      ],
    },
    {
      key: "recording",
      label: "فایل صوتی",
      icon: "Mic",
      fields: [
        {
          key: "record_file",
          label: "فایل صوتی",
          type: "file",
          required: false,
          accept: "audio/*",
          span: 12,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره تماس", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};

/**
 * Quick Call Form — lightweight version for QuickCallModal.
 */
export const QUICK_CALL_FORM = {
  title: "ثبت تماس سریع",
  tabs: null,
  fields: [
    {
      key: "customer",
      label: "مشتری",
      type: "search_select",
      required: true,
      placeholder: "جستجوی مشتری...",
      asyncSource: API_ENDPOINTS.CUSTOMERS.LIST.url,
      searchFields: ["full_name", "phone"],
      displayField: "full_name",
      validation: { required: "انتخاب مشتری الزامی است" },
      span: 12,
    },
    {
      key: "call_type",
      label: "نوع تماس",
      type: "select",
      required: true,
      options: [
        { value: "incoming", label: "ورودی" },
        { value: "outgoing", label: "خروجی" },
      ],
      defaultValue: "outgoing",
      validation: { required: "نوع تماس الزامی است" },
      span: 6,
    },
    {
      key: "called_at",
      label: "زمان تماس",
      type: "datetime",
      required: true,
      defaultValue: "now",
      validation: { required: "زمان تماس الزامی است" },
      span: 6,
    },
    {
      key: "result",
      label: "نتیجه تماس",
      type: "select",
      required: true,
      options: [
        { value: "answered", label: "پاسخ داده" },
        { value: "no_answer", label: "بدون پاسخ" },
        { value: "busy", label: "مشغول" },
        { value: "interested", label: "علاقه‌مند" },
        { value: "not_interested", label: "عدم علاقه" },
        { value: "follow_up", label: "نیاز به پیگیری" },
        { value: "visit_booked", label: "قرار بازدید" },
      ],
      validation: { required: "نتیجه تماس الزامی است" },
      span: 12,
    },
    {
      key: "note",
      label: "یادداشت",
      type: "textarea",
      required: false,
      placeholder: "جزئیات تماس...",
      rows: 3,
      span: 12,
    },
  ],
  actions: {
    submit: { label: "ثبت تماس", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};
