
/**
 * Create/Edit Call Form
 * Multi-tab: basic, result, followup
 */
export const CALL_FORM = {
  title: "تماس",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات تماس",
      icon: "Phone",
      fields: [
        {
          key: "customer",
          label: "مشتری / تماس‌گیرنده",
          type: "search_select",
          required: true,
          placeholder: "جستجوی مشتری...",
          asyncSource: "/api/customers/",
          searchFields: ["full_name", "phone", "national_id"],
          displayField: "full_name",
          validation: { required: "انتخاب مشتری الزامی است" },
          span: 12,
        },
        {
          key: "call_type",
          label: "نوع تماس",
          type: "select",
          required: true,
          placeholder: "انتخاب نوع",
          options: [
            { value: "inbound", label: "ورودی" },
            { value: "outbound", label: "خروجی" },
            { value: "missed", label: "از دست رفته" },
            { value: "follow_up", label: "پیگیری" },
          ],
          defaultValue: "outbound",
          validation: { required: "نوع تماس الزامی است" },
          span: 6,
        },
        {
          key: "called_at",
          label: "زمان تماس",
          type: "datetime",
          required: true,
          defaultValue: "now",
          validation: { required: "زمان تماس الزامی است" },
          span: 6,
        },
        {
          key: "handled_by",
          label: "اپراتور",
          type: "search_select",
          required: false,
          placeholder: "جستجوی اپراتور...",
          asyncSource: "/api/users/?is_active=true",
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          span: 12,
        },
        {
          key: "related_listing",
          label: "آگهی مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی آگهی...",
          asyncSource: "/api/listings/",
          searchFields: ["title", "external_id"],
          displayField: "title",
          span: 6,
        },
        {
          key: "related_property",
          label: "ملک مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی ملک...",
          asyncSource: "/api/properties/",
          searchFields: ["title", "property_code"],
          displayField: "title",
          span: 6,
        },
        {
          key: "duration",
          label: "مدت تماس (ثانیه)",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱۲۰",
          min: 0,
          span: 6,
        },
        {
          key: "record_file",
          label: "فایل صوتی",
          type: "file",
          required: false,
          accept: "audio/*",
          span: 6,
        },
      ],
    },
    {
      key: "result",
      label: "نتیجه",
      icon: "CheckCircle",
      fields: [
        {
          key: "result",
          label: "نتیجه تماس",
          type: "select",
          required: true,
          placeholder: "انتخاب نتیجه",
          options: [
            { value: "answered", label: "پاسخ داده" },
            { value: "no_answer", label: "بدون پاسخ" },
            { value: "busy", label: "مشغول" },
            { value: "interested", label: "علاقه‌مند" },
            { value: "not_interested", label: "عدم علاقه" },
            { value: "follow_up", label: "نیاز به پیگیری" },
            { value: "visit_booked", label: "قرار بازدید" },
          ],
          validation: { required: "نتیجه تماس الزامی است" },
          span: 12,
        },
        {
          key: "note",
          label: "یادداشت",
          type: "textarea",
          required: false,
          placeholder: "جزئیات تماس...",
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "followup",
      label: "پیگیری بعدی",
      icon: "CalendarClock",
      condition: (values) => ["follow_up", "interested", "visit_booked"].includes(values.result),
      fields: [
        {
          key: "next_follow_up_at",
          label: "تاریخ پیگیری بعدی",
          type: "datetime",
          required: false,
          placeholder: "انتخاب تاریخ",
          span: 6,
        },
        {
          key: "follow_up_done",
          label: "پیگیری انجام شد",
          type: "checkbox",
          required: false,
          defaultValue: false,
          span: 6,
        },
        {
          key: "follow_up_note",
          label: "توضیحات پیگیری",
          type: "textarea",
          required: false,
          placeholder: "جزئیات پیگیری بعدی...",
          rows: 3,
          span: 12,
        },
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره تماس", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};

/**
 * Quick Register Call Form (simplified — used in listing/property context)
 */
export const QUICK_CALL_FORM = {
  title: "ثبت تماس سریع",
  tabs: null,
  fields: [
    {
      key: "result",
      label: "نتیجه تماس",
      type: "select",
      required: true,
      placeholder: "انتخاب نتیجه",
      options: [
        { value: "answered", label: "پاسخ داده" },
        { value: "no_answer", label: "بدون پاسخ" },
        { value: "busy", label: "مشغول" },
        { value: "interested", label: "علاقه‌مند" },
        { value: "not_interested", label: "عدم علاقه" },
        { value: "follow_up", label: "نیاز به پیگیری" },
        { value: "visit_booked", label: "قرار بازدید" },
      ],
      validation: { required: "نتیجه الزامی است" },
      span: 12,
    },
    {
      key: "note",
      label: "یادداشت",
      type: "textarea",
      required: false,
      placeholder: "جزئیات تماس...",
      rows: 3,
      span: 12,
    },
    {
      key: "next_follow_up_at",
      label: "تاریخ پیگیری بعدی",
      type: "datetime",
      required: false,
      condition: (values) => values.result === "follow_up" || values.result === "interested" || values.result === "visit_booked",
      span: 12,
    },
  ],
  actions: {
    submit: { label: "ثبت", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};