export const CALL_FORM = {
  title: "تماس",
  tabs: [
    {
      key: "basic",
      label: "اطلاعات تماس",
      icon: "Phone",
      fields: [
        {
          key: "customer",
          label: "مشتری / تماس‌گیرنده",
          type: "search_select",
          required: true,
          placeholder: "جستجوی مشتری...",
          asyncSource: "/api/customers/",
          searchFields: ["full_name", "phone"],
          displayField: "full_name",
          validation: { required: "انتخاب مشتری الزامی است" },
          span: 12,
        },
        {
          key: "call_type",
          label: "نوع تماس",
          type: "select",
          required: true,
          placeholder: "انتخاب نوع",
          options: [
            { value: "incoming", label: "ورودی" },   // ← incoming
            { value: "outgoing", label: "خروجی" },   // ← outgoing
          ],
          defaultValue: "outgoing",
          validation: { required: "نوع تماس الزامی است" },
          span: 6,
        },
        {
          key: "called_at",
          label: "زمان تماس",
          type: "datetime",
          required: true,
          defaultValue: "now",
          validation: { required: "زمان تماس الزامی است" },
          span: 6,
        },
        {
          key: "listing",          
          label: "آگهی مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی آگهی...",
          asyncSource: "/api/listing/list",
          searchFields: ["title", "external_id"],
          displayField: "title",
          span: 6,
        },
        {
          key: "property",          
          label: "ملک مرتبط",
          type: "search_select",
          required: false,
          placeholder: "جستجوی ملک...",
          asyncSource: "/api/property/list",
          searchFields: ["title", "property_code"],
          displayField: "title",
          span: 6,
        },
        {
          key: "call_duration",     
          label: "مدت تماس (ثانیه)",
          type: "number",
          required: false,
          placeholder: "مثلاً ۱۲۰",
          min: 0,
          span: 6,
        },
        {
          key: "record_file",
          label: "فایل صوتی",
          type: "file",
          required: false,
          accept: "audio/*",
          span: 6,
        },
      ],
    },
    {
      key: "result",
      label: "نتیجه",
      icon: "CheckCircle",
      fields: [
        {
          key: "result",
          label: "نتیجه تماس",
          type: "select",
          required: true,
          placeholder: "انتخاب نتیجه",
          options: [
            { value: "answered", label: "پاسخ داده" },
            { value: "no_answer", label: "بدون پاسخ" },
            { value: "busy", label: "مشغول" },
            { value: "interested", label: "علاقه‌مند" },
            { value: "not_interested", label: "عدم علاقه" },
            { value: "follow_up", label: "نیاز به پیگیری" },
            { value: "visit_booked", label: "قرار بازدید" },
          ],
          validation: { required: "نتیجه تماس الزامی است" },
          span: 12,
        },
        {
          key: "note",
          label: "یادداشت",
          type: "textarea",
          required: false,
          placeholder: "جزئیات تماس...",
          rows: 4,
          span: 12,
        },
      ],
    },
    {
      key: "followup",
      label: "پیگیری بعدی",
      icon: "CalendarClock",
      condition: (values) => ["follow_up", "interested", "visit_booked"].includes(values.result),
      fields: [
        {
          key: "next_follow_up_at",
          label: "تاریخ پیگیری بعدی",
          type: "datetime",
          required: false,
          placeholder: "انتخاب تاریخ",
          span: 6,
        },
        {
          key: "follow_up_done",
          label: "پیگیری انجام شد",
          type: "checkbox",
          required: false,
          defaultValue: false,
          span: 6,
        },
        
      ],
    },
  ],
  actions: {
    submit: { label: "ذخیره تماس", variant: "primary" },
    cancel: { label: "انصراف", variant: "ghost" },
  },
};