# Generated by Django 6.0.5 on 2026-05-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('customer_type', models.CharField(choices=[('buyer', 'خریدار'), ('renter', 'مستاجر'), ('investor', 'سرمایه گذار')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=50)),
                ('budget_min', models.BigIntegerField(blank=True, null=True)),
                ('budget_max', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'برنامه ریزی شده'), ('completed', 'انجام شده'), ('canceled', 'لغو شده'), ('no_show', 'عدم حضور مشتری')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'property_visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('incoming', 'ورودی'), ('outgoing', 'خروجی')], max_length=20)),
                ('result', models.CharField(choices=[('answered', 'پاسخ داده شد'), ('no_answer', 'پاسخ نداد'), ('busy', 'مشغول'), ('interested', 'علاقه مند'), ('not_interested', 'عدم تمایل'), ('follow_up', 'نیاز به پیگیری'), ('visit_booked', 'بازدید ثبت شد')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('call_duration', models.PositiveIntegerField(default=0)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handled_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-called_at'],
            },
        ),
    ]
