export const LISTING_FILTERS = [
  {
    key: "search",
    type: "search",
    label: "جستجو",
    placeholder: "عنوان، شماره تلفن، توضیحات...",
  },
  {
    key: "status",
    type: "select",
    label: "وضعیت",
    optionsKey: "statuses",
    options: [
      { value: "draft", label: "پیش نویس" },
      { value: "active", label: "فعال" },
      { value: "paused", label: "متوقف" },
      { value: "sold", label: "فروخته شده" },
      { value: "rented", label: "اجاره داده شده" },
      { value: "expired", label: "منقضی شده" },
      { value: "archived", label: "آرشیو شده" },
    ],
  },
  {
    key: "source",
    type: "select",
    label: "منبع",
    optionsKey: "sources",
    options: [
      { value: "divar", label: "دیوار" },
      { value: "sheypoor", label: "شیپور" },
      { value: "other", label: "سایر" },
    ],
  },
  {
    key: "listed_area",
    type: "range",
    label: "متراژ",
    unit: "متر",
    min: 0,
    max: 10000,
    step: 10,
  },
  {
    key: "created_by",
    type: "select",
    label: "ثبت کننده",
    optionsKey: "users",
    options: [
      { value: "1", label: "مدیریت ملک جو" },
      { value: "2", label: "کارشناس ۱ - علی رضایی" },
      { value: "3", label: "کارشناس ۲ - سارا محمدی" },
      { value: "4", label: "کارشناس ۳ - حسن کریمی" },
    ],
  },
];