import {
  LISTING_STATUS_CONFIG,
  LISTING_REVIEW_STATUS_CONFIG,
} from "@/features/listings/config";
import {  PROPERTY_DEAL_TYPE_CONFIG,
} from "@/features/properties/config"

/**
 * Listing Filters Config
 * Backend: listing.Listing
 * 
 * Quick: search, deal_type, status, review_status, price_range, area
 * Advanced: source, date ranges, scraping fields, room/floor/year, media, failures
 */

export const LISTING_QUICK_FILTERS = [
  {
    key: "search",
    label: "جستجو",
    type: "search",
    placeholder: "عنوان، شناسه خارجی، توضیحات...",
    fields: ["title", "external_id", "description"],
    placement: "bar",
  },
  {
    key: "deal_type",
    label: "نوع معامله",
    type: "multi_select",
    placement: "bar",
    options: [
      { value: "sale", label: "فروش" },
      { value: "rent", label: "اجاره" },
      { value: "mortgage", label: "رهن" },
    ],
    // computed from listed_sale_price / listed_rent_amount / listed_mortgage_amount
  },
  {
    key: "status",
    label: "وضعیت آگهی",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(LISTING_STATUS_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "review_status",
    label: "وضعیت بررسی",
    type: "multi_select",
    placement: "bar",
    options: Object.entries(LISTING_REVIEW_STATUS_CONFIG).map(([value, cfg]) => ({
      value,
      label: cfg.label,
    })),
  },
  {
    key: "price_range",
    label: "محدوده قیمت",
    type: "range",
    placement: "bar",
    min_key: "price_min",
    max_key: "price_max",
    step: 1_000_000,
    unit: "تومان",
    fields: ["listed_sale_price", "listed_rent_amount", "listed_mortgage_amount"],
  },
  {
    key: "area",
    label: "متراژ",
    type: "range",
    placement: "bar",
    min_key: "area_min",
    max_key: "area_max",
    step: 5,
    unit: "متر",
  },
];

export const LISTING_ADVANCED_FILTERS = [
  {
    key: "source",
    label: "منبع",
    type: "multi_select",
    placement: "drawer",
    async: true,
    endpoint: "/api/listing/sources/",
    optionLabel: "name",
    optionValue: "id",
  },
  {
    key: "created_by",
    label: "ثبت‌کننده",
    type: "search_select",
    placement: "drawer",
    async: true,
    endpoint: "/api/accounts/users/",
    search_fields: ["full_name", "phone"],
    optionLabel: "full_name",
    optionValue: "id",
  },
  {
    key: "room_count",
    label: "تعداد اتاق",
    type: "range",
    placement: "drawer",
    min_key: "room_min",
    max_key: "room_max",
    step: 1,
    unit: "اتاق",
  },
  {
    key: "floor_number",
    label: "طبقه",
    type: "range",
    placement: "drawer",
    min_key: "floor_min",
    max_key: "floor_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "total_floors",
    label: "تعداد طبقات",
    type: "range",
    placement: "drawer",
    min_key: "total_floors_min",
    max_key: "total_floors_max",
    step: 1,
    unit: "طبقه",
  },
  {
    key: "build_year",
    label: "سال ساخت",
    type: "range",
    placement: "drawer",
    min_key: "year_min",
    max_key: "year_max",
    step: 1,
    unit: "",
  },
  {
    key: "has_media",
    label: "دارای رسانه",
    type: "toggle",
    placement: "drawer",
    filter: (row) => row.media_count > 0,
  },
  {
    key: "has_leads",
    label: "دارای سرنخ",
    type: "toggle",
    placement: "drawer",
    filter: (row) => row.leads_count > 0,
  },
  {
    key: "pictures_match",
    label: "تطابق تصاویر",
    type: "select",
    placement: "drawer",
    options: [
      { value: "true", label: "تطابق دارد" },
      { value: "false", label: "تطابق ندارد" },
      { value: "null", label: "بررسی نشده" },
    ],
  },
  {
    key: "consecutive_failures",
    label: "خطای متوالی",
    type: "range",
    placement: "drawer",
    min_key: "failures_min",
    max_key: "failures_max",
    step: 1,
    unit: "بار",
  },
  {
    key: "is_removed",
    label: "حذف‌شده از منبع",
    type: "toggle",
    placement: "drawer",
    filter: (row) => !!row.removal_detected_at,
  },
  {
    key: "first_seen",
    label: "اولین مشاهده",
    type: "date_range",
    placement: "drawer",
    from_key: "first_seen_from",
    to_key: "first_seen_to",
  },
  {
    key: "last_seen",
    label: "آخرین مشاهده",
    type: "date_range",
    placement: "drawer",
    from_key: "last_seen_from",
    to_key: "last_seen_to",
  },
  {
    key: "published_at",
    label: "تاریخ انتشار",
    type: "date_range",
    placement: "drawer",
    from_key: "published_from",
    to_key: "published_to",
  },
  {
    key: "expires_at",
    label: "تاریخ انقضا",
    type: "date_range",
    placement: "drawer",
    from_key: "expires_from",
    to_key: "expires_to",
  },
  {
    key: "created_at",
    label: "تاریخ ثبت در سیستم",
    type: "date_range",
    placement: "drawer",
    from_key: "created_from",
    to_key: "created_to",
  },
  {
    key: "price_per_meter",
    label: "قیمت هر متر",
    type: "range",
    placement: "drawer",
    min_key: "ppm_min",
    max_key: "ppm_max",
    step: 100_000,
    unit: "تومان",
  },
  {
    key: "deposit_amount",
    label: "ودیعه",
    type: "range",
    placement: "drawer",
    min_key: "deposit_min",
    max_key: "deposit_max",
    step: 1_000_000,
    unit: "تومان",
  },
  {
    key: "rent_amount",
    label: "اجاره ماهیانه",
    type: "range",
    placement: "drawer",
    min_key: "rent_min",
    max_key: "rent_max",
    step: 500_000,
    unit: "تومان",
  },
];

export const LISTING_ALL_FILTERS = [...LISTING_QUICK_FILTERS, ...LISTING_ADVANCED_FILTERS];