# Generated by Django 5.2.16 on 2026-08-09 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sources",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("url", models.URLField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("active", "فعال"),
                            ("paused", "متوقف"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("expired", "منقضی شده"),
                            ("archived", "آرشیو"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "بررسی نشده"),
                            ("shortlisted", "منتخب"),
                            ("rejected", "رد شده"),
                            ("promoted", "تبدیل به ملک"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("listed_sale_price", models.BigIntegerField(blank=True, null=True)),
                (
                    "listed_price_per_meter",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "listed_mortgage_amount",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "listed_deposit_amount",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("listed_rent_amount", models.BigIntegerField(blank=True, null=True)),
                ("listed_area", models.PositiveIntegerField(blank=True, null=True)),
                ("build_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("room_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("floor_number", models.IntegerField(blank=True, null=True)),
                (
                    "total_floors",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("pictures_match_property", models.BooleanField(blank=True, null=True)),
                ("media_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("leads_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_changed_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("removal_detected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("latest_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="properties.property",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="listing.source",
                    ),
                ),
            ],
            options={
                "db_table": "listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingStatusHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("active", "فعال"),
                            ("paused", "متوقف"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("expired", "منقضی شده"),
                            ("archived", "آرشیو"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش نویس"),
                            ("active", "فعال"),
                            ("paused", "متوقف"),
                            ("sold", "فروخته شده"),
                            ("rented", "اجاره داده شده"),
                            ("expired", "منقضی شده"),
                            ("archived", "آرشیو"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="listing.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["source", "status", "last_checked_at"],
                name="listings_source__3d377b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["review_status", "last_checked_at"],
                name="listings_review__db90f7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source", "external_id"),
                name="unique_listing_source_external_id",
            ),
        ),
    ]
