# Generated by Django 6.0.5 on 2026-07-30 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('properties', '0002_alter_property_property_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='build_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='listing',
            name='first_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='latest_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_mortgage_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_price_per_meter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pictures_match_property',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='removal_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'بررسی نشده'), ('shortlisted', 'منتخب'), ('rejected', 'رد شده'), ('promoted', 'تبدیل به ملک')], db_index=True, default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['source', 'status', 'last_checked_at'], name='listings_source__3d377b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['review_status', 'last_checked_at'], name='listings_review__db90f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_listing_source_external_id'),
        ),
    ]
