# Generated by Django 5.2.16 on 2026-09-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0003_listing_advertiser_classification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-created_at"],
                "permissions": [("promote_listing", "Can promote listing")],
            },
        ),
    ]
