# Generated by Django 6.0.5 on 2026-09-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_options'),
        ('locations', '0002_divarneighborhood_zone_city_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('rent-residential', 'اجارهٔ مسکونی'), ('buy-residential', 'فروش مسکونی'), ('buy-commercial-property', 'فروش اداری و تجاری'), ('rent-commercial-property', 'اجارهٔ اداری و تجاری')], db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='listing',
            name='divar_neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='locations.divarneighborhood'),
        ),
    ]
