# Generated by Django 5.2.16 on 2026-09-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0006_backfill_listing_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("promote_listing", "Can promote listing"),
                    ("review_listing", "Can review listing"),
                ],
            },
        ),
    ]
