# Generated by Django 6.0.5 on 2026-05-30 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view', 'مشاهده'), ('login', 'ورود'), ('logout', 'خروج'), ('status_change', 'تغییر وضعیت'), ('api_call', 'درخواست API')], max_length=30)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=50)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_full_url', models.TextField(blank=True)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('api', 'API'), ('admin', 'ادمین'), ('system', 'سیستم'), ('cron', 'کرون جاب')], default='api', max_length=20)),
                ('level', models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('error', 'خطا'), ('critical', 'بحرانی')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_meter', models.BigIntegerField(blank=True, null=True)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('mortgage_amount', models.BigIntegerField(blank=True, null=True)),
                ('deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('monthly_rent', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'price_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
