# Generated by Django 5.2.16 on 2026-07-28 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_meter', models.BigIntegerField(blank=True, null=True)),
                ('sale_price', models.BigIntegerField(blank=True, null=True)),
                ('mortgage_amount', models.BigIntegerField(blank=True, null=True)),
                ('deposit_amount', models.BigIntegerField(blank=True, null=True)),
                ('monthly_rent', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='properties.property')),
            ],
            options={
                'db_table': 'price_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('view', 'مشاهده'), ('login', 'ورود'), ('logout', 'خروج'), ('status_change', 'تغییر وضعیت'), ('api_call', 'درخواست API')], max_length=30)),
                ('source', models.CharField(choices=[('api', 'API'), ('admin', 'پنل ادمین'), ('system', 'سیستم'), ('cron', 'Cron Job')], default='api', max_length=20)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10)),
                ('outcome', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق')], default='success', max_length=10)),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.CharField(db_index=True, max_length=50)),
                ('old_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('error_trace', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='activity_lo_user_id_072db3_idx'), models.Index(fields=['action'], name='activity_lo_action_b49f28_idx'), models.Index(fields=['entity_type'], name='activity_lo_entity__97ab7c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__5a4970_idx'), models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'), models.Index(fields=['request_id'], name='activity_lo_request_8f24ba_idx'), models.Index(fields=['source'], name='activity_lo_source_33a666_idx'), models.Index(fields=['level'], name='activity_lo_level_7afc2b_idx'), models.Index(fields=['outcome'], name='activity_lo_outcome_aabdbd_idx')],
            },
        ),
    ]
